### ISSUE TITLE
add noise support

### ISSUE THREAD

**Issue by philsupertramp** [godesteem/bucket-engine#11]
add https://github.com/joshinils/noise vendors

**Comment by joshinils** [comment]
aber bitte nicht als sumodul, da käme zu viel müll mit:

- noise beinhaltet:
- eigenen kram um die pge anzusprechen, cmake etc.
  - olcPixelGameEngine mit beispielen, etc. als submodul
  - plane mit 
    - kram um die pge anzusprechen, cmake etc.
    - olcPixelGameEngine mit beispielen, etc. als submodul

du kannst einfach den code rüberkopieren als datei, und einmal im commit auf mein repo verweisen, oder auch gleichzeitig darauf, wo ich das her hab:
https://gist.github.com/Markyparky56/e0fd43e847ac53068603130df3e8e560

oder du fügst den link oben in diese nachricht mit ein, dann ist es immer da

**Comment by philipp-zettl** [comment]
das war der Plan =)
