### ISSUE TITLE
move logger to function

### ISSUE THREAD

**Issue by joshinils** [godesteem/bucket-engine#12]
see:
https://godbolt.org/z/NtnA32

the actual call will be optimized away if it is set to not include the respective logging functionality.
of course this may take longer to compile, but i think it will be better suited to debugging than using macros.
(please dont use macros)

**Comment by joshinils** [comment]
@philsupertramp asign this to me if you want me to do the change, or close this issue otherwise

**Comment by philipp-zettl** [comment]
@joshinils I understand. What's your reason to remove macros?

**Comment by philsupertramp** [comment]
@joshinils I understand. What's your reason to remove macros?

**Comment by joshinils** [comment]
You cant debug them, ie you cant step through it and watch what happens

**Comment by philsupertramp** [comment]
works for me, at least in multi-line macros. But anyways I see problems especially if a macro is overloaded.
