### ISSUE TITLE
should there be non-class-member functions in the math library?

### ISSUE THREAD

**Issue by joshinils** [godesteem/bucket-engine#19]
e.g.
https://github.com/godesteem/bucket-engine/blob/63f7e9fbd41c2f19ea3184b48c640b91267be569/engine/lib/math/vector.h#L57 https://github.com/godesteem/bucket-engine/blob/63f7e9fbd41c2f19ea3184b48c640b91267be569/engine/lib/math/vector.h#L60 https://github.com/godesteem/bucket-engine/blob/63f7e9fbd41c2f19ea3184b48c640b91267be569/engine/lib/math/vector.h#L63 https://github.com/godesteem/bucket-engine/blob/63f7e9fbd41c2f19ea3184b48c640b91267be569/engine/lib/math/vector.h#L66

these could all be member functions, that would also mean cleaner code to read as one would always apply something to an object

if you want, i will move these in the respective classes

**Comment by philsupertramp** [comment]
yes, please.
