### ISSUE TITLE
what should Orthogonal return?

### ISSUE THREAD

**Issue by joshinils** [godesteem/bucket-engine#20]
a unit vector, as the test suggests, but simply being length one doesnt suffice, only having ine value be 1 also does not suffice, which one?
then to which is this orthogonal to?

should this rather be renamed to `standardbasisvector`? then which one of those should it return? maybe with an index as template parameter and default value 1 meaning a 1 at the first position?

**Comment by philsupertramp** [comment]
@joshinils damn, I forgot to post the comment...

Seems like I didn't describe it properly. 
We need a implementation of `glm::ortho` which can be found [here](https://glm.g-truc.net/0.9.2/api/a00245.html#ga71777a3b1d4fe1729cccf6eda05c8127) another site with a good description can be found [here](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glOrtho.xml).

we need both signatures for that, meaning:
```c++
ortho(T const& left, T const& right, T const& bottom, T const& top);
ortho(T const& left, T const& right, T const& bottom, T const& top, T const& zNear, T const& zFar);
```

**Comment by joshinils** [comment]
sure, i can add that for `matrix<4,4>`,  but i was asking about the following: https://github.com/godesteem/vendors/blob/4dbe28e47a5aa33ee55ccff2aefdaff0a8c9602a/math/vector.h#L47 what is that function?
aswell regarding these tests for said function: https://github.com/godesteem/bucket-engine/blob/7a2d8ced03f41bff2e4bdf0d08d320b78ff255d5/engine/tests/test_math.h#L39

**Comment by joshinils** [comment]
@philsupertramp please verify that https://github.com/godesteem/bucket-engine/blob/2a27b123597b430092603af7ea1b55ed686e81a0/engine/lib/math/matrix.h#L245 and https://github.com/godesteem/bucket-engine/blob/2a27b123597b430092603af7ea1b55ed686e81a0/engine/tests/test_math.h#L62 are what you want

**Comment by philsupertramp** [comment]
> sure, i can add that for `matrix<4,4>`, but i was asking about the following: https://github.com/godesteem/vendors/blob/4dbe28e47a5aa33ee55ccff2aefdaff0a8c9602a/math/vector.h#L47 what is that function?
> aswell regarding these tests for said function:
> 
> https://github.com/godesteem/bucket-engine/blob/7a2d8ced03f41bff2e4bdf0d08d320b78ff255d5/engine/tests/test_math.h#L39

please drop it, it's **wrong**.

**Comment by philsupertramp** [comment]
> @philsupertramp please verify that
> 
> https://github.com/godesteem/bucket-engine/blob/2a27b123597b430092603af7ea1b55ed686e81a0/engine/lib/math/matrix.h#L245
> 
> and
> https://github.com/godesteem/bucket-engine/blob/2a27b123597b430092603af7ea1b55ed686e81a0/engine/tests/test_math.h#L62
> 
> are what you want

I will need to see it working. The current branch does not compile. Is it a platform issue, or did you configure something without adding it to the project?

Also need to spend some time understanding the implementation of matrix
