### ISSUE TITLE
Add default values for members of Buffer class

### ISSUE THREAD

**Issue by joshinils** [godesteem/bucket-engine#22]
this line: https://github.com/godesteem/bucket-engine/blob/7a2d8ced03f41bff2e4bdf0d08d320b78ff255d5/engine/src/engine/renderer/Buffer.h#L46 generates a cppcore-guidelines [Type.6](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#SS-type) warning for me in vs2019,
consider [this answer](https://stackoverflow.com/a/36601200/10314791) for how to act upon this

**Comment by philsupertramp** [comment]
I assume `Offset` causes the issue?
