### ISSUE TITLE
Create test example and small "testing docs"

### ISSUE THREAD

**Issue by philsupertramp** [godesteem/bucket-engine#29]
we need general guidlines and an example test in `./engine/tests/README.md` to add to our docs.

- [x] create docs in readme file, current version is just a scetch and can be dropped
- [ ] add file to doc generation `./docs/doxygen.conf` attribute `INPUTE`

**Comment by joshinils** [comment]
@philsupertramp is this closed?

**Comment by philsupertramp** [comment]
fixed in https://github.com/godesteem/bucket-engine/commit/e4f48dbf92b138b251b7e55a010e8fde5ee0521e#diff-5a9e908a7ddd3a7669f78d326e1cd705
