### ISSUE TITLE
math lib

### ISSUE THREAD

**Issue by philsupertramp** [godesteem/bucket-engine#3]
we want to get rid of glm's vec

Following functionalities including their morphisms are mandatory:
- vec3
- mat4

Morphisms:
- translate: vec3 -> mat4
  - translates vec3 positional to mat4 transformation matrix
- orthogonal: (float left, float right, float top, float bottom, float zNear, float zFar) -> mat4
  - generates orthogonal matrix to given base
- lookAt: () -> mat4

**Comment by joshinils** [comment]
if you could create a branch with a skeleton class (named mat, math, vec, or something appropriate) i could start implementing this.
if you would help me test this that would be even better, e.g. have a class with tests for this new class, and/or a way to try the tests in-engine, so i have a mnenu where i can click buttons and enter values for testing the functions

**Comment by philsupertramp** [comment]
> if you could create a branch with a skeleton class (named mat, math, vec, or something appropriate) i could start implementing this.
> if you would help me test this that would be even better, e.g. have a class with tests for this new class, and/or a way to try the tests in-engine, so i have a mnenu where i can click buttons and enter values for testing the functions

Will provide branch with existing code, including a testing framwork tomorrow.

**Comment by philsupertramp** [comment]
@joshinils see https://github.com/godesteem/bucket-engine/pull/14
